import React, { useState } from 'react';
import type { Company } from '../types';
import { Mail, FileText, Check, Copy, Sparkles, MessageCircle } from 'lucide-react';

interface OutreachViewProps {
  companies: Company[];
}

export const OutreachView: React.FC<OutreachViewProps> = ({ companies }) => {
  const outreachLeads = companies.filter(c => c.intentScore >= 51);
  const [selectedLeadId, setSelectedLeadId] = useState<string>(outreachLeads[0]?.id || '');
  const [activeTab, setActiveTab] = useState<'email' | 'brief' | 'community'>('email');
  const [copied, setCopied] = useState(false);

  const selectedLead = companies.find(c => c.id === selectedLeadId);

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const generateEmail = (lead: Company) => {
    if (lead.targetTier === 'SMB') {
      return `Subject: Helping ${lead.name} setup job scheduling & digital presence

Hi team at ${lead.name},

I saw your recent registration in ${lead.country} (${lead.registrySource}) and noticed you've been expanding your operations recently!

Many local businesses in ${lead.industry} run into admin headaches with manual invoicing and dispatch tracking. We specialize in setting up automated scheduling (like ServiceM8/Tradify) and getting your Google Business Profile ranking #1 in your postcode.

Would you be open to a 5-minute chat this Thursday to see how we can save your team 10 hours a week on admin?

Best,
LogikSense Local Intelligence Squad`;
    }

    return `Subject: Partnership request: scaling ${lead.name} operations

Hi there,

I’m reaching out from LogikSense.ai. I noticed your active signals regarding ERP consolidation and recent technology migration initiatives.

We specialize in providing tailored infrastructure automation and system integration services.

Would you be open to a brief 10-minute introductory call next Tuesday to explore how we can support your scaling goals?

Best regards,
LogikSense Sales Intelligence Agent`;
  };

  const generateBrief = (lead: Company) => {
    return `=========================================
PRE-MEETING INTEL BRIEF (v3): ${lead.name.toUpperCase()}
Generated by: Agent 12 (Meeting Prep)
Jurisdiction: ${lead.country} (${lead.registrySource})
Target Tier: ${lead.targetTier}
=========================================

1. RECENT SIGNALS & INTENT TRACEABILITY
-----------------------------------------
* Composite v3 Intent Score: ${lead.intentScore}/100 (${lead.classification})
${lead.signals.map(s => `  - [${s.type}]: ${s.description} (Source: ${s.source})`).join('\n')}

2. KEY RISKS & DIGITAL GAP ANALYSIS
------------------------------------
* Risk Summary: ${lead.riskSummary}
* Digital Gap Status: ${lead.hasDigitalGap ? 'ACTIVE DIGITAL GAP DETECTED (High Urgency)' : 'Standard Digital Presence'}

3. RECOMMENDED PITCH ANGLE
--------------------------
* ${lead.oppSummary}
`;
  };

  const generateCommunityPost = (lead: Company) => {
    return `[COMMUNITY PLATFORM SCRIPT - FB GROUPS / LOCAL REDDIT]
Target Community Signal: ${lead.signals.find(s => s.type.includes('Local'))?.description || 'Local trade recommendation request'}

Recommended DM Response / Comment:
"Hi! Saw your post regarding admin and scheduling software for local businesses. We actually just helped another team in your area set up automated invoicing and job tracking so they don't have to spend Sundays doing paperwork. Happy to share what worked for them if you'd like!"`;
  };

  return (
    <div style={{ display: 'grid', gridTemplateColumns: '0.8fr 1.2fr', gap: '20px', animation: 'fadeIn 0.5s ease-in-out' }}>
      
      {/* High-Intent Lead Selector */}
      <div className="glass-panel" style={{ padding: '24px', display: 'flex', flexDirection: 'column', gap: '15px' }}>
        <h2 style={{ fontFamily: 'var(--font-display)', fontSize: '20px', fontWeight: 700 }}>Outreach Queue (v3)</h2>
        <p style={{ color: 'var(--text-muted)', fontSize: '13px', marginBottom: '10px' }}>
          Qualifying leads matching high or immediate SLA action protocols (Score ≥ 51).
        </p>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '10px', overflowY: 'auto', maxHeight: '550px' }}>
          {outreachLeads.map(lead => (
            <div 
              key={lead.id}
              onClick={() => setSelectedLeadId(lead.id)}
              style={{ 
                padding: '14px', 
                background: selectedLeadId === lead.id ? 'rgba(139, 92, 246, 0.08)' : 'rgba(255,255,255,0.02)',
                borderRadius: '10px',
                border: '1px solid',
                borderColor: selectedLeadId === lead.id ? 'var(--color-primary)' : 'rgba(255,255,255,0.05)',
                cursor: 'pointer',
                transition: 'all 0.2s',
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center'
              }}
            >
              <div>
                <div style={{ fontWeight: 600, fontSize: '14px', display: 'flex', alignItems: 'center', gap: '6px' }}>
                  {lead.name}
                  <span style={{ fontSize: '10px', background: 'rgba(255,255,255,0.05)', padding: '2px 6px', borderRadius: '4px' }}>{lead.targetTier}</span>
                </div>
                <div style={{ fontSize: '12px', color: 'var(--text-muted)' }}>{lead.country} ({lead.industry})</div>
              </div>
              <span style={{ 
                background: lead.intentScore >= 76 ? 'rgba(16, 185, 129, 0.15)' : 'rgba(139, 92, 246, 0.15)',
                color: lead.intentScore >= 76 ? 'var(--color-success)' : 'var(--color-primary)',
                padding: '4px 8px',
                borderRadius: '6px',
                fontSize: '11px',
                fontWeight: 700
              }}>
                {lead.intentScore}
              </span>
            </div>
          ))}
        </div>
      </div>

      {/* Editor & Generator Dashboard */}
      {selectedLead ? (
        <div className="glass-panel" style={{ padding: '24px', display: 'flex', flexDirection: 'column', gap: '20px' }}>
          
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid var(--border-glow)', paddingBottom: '16px' }}>
            <div>
              <div style={{ fontSize: '12px', color: 'var(--text-muted)' }}>ACTIVE TARGET • {selectedLead.targetTier}</div>
              <h3 style={{ fontFamily: 'var(--font-display)', fontSize: '20px', fontWeight: 700 }}>{selectedLead.name}</h3>
            </div>
            
            <div style={{ display: 'flex', background: 'rgba(255,255,255,0.03)', padding: '4px', borderRadius: '8px' }}>
              <button 
                onClick={() => setActiveTab('email')}
                style={{ background: activeTab === 'email' ? 'var(--color-primary)' : 'none', border: 'none', color: 'white', padding: '6px 12px', borderRadius: '6px', cursor: 'pointer', fontSize: '13px', display: 'flex', alignItems: 'center', gap: '6px' }}
              >
                <Mail size={14} /> Email
              </button>
              <button 
                onClick={() => setActiveTab('brief')}
                style={{ background: activeTab === 'brief' ? 'var(--color-primary)' : 'none', border: 'none', color: 'white', padding: '6px 12px', borderRadius: '6px', cursor: 'pointer', fontSize: '13px', display: 'flex', alignItems: 'center', gap: '6px' }}
              >
                <FileText size={14} /> Brief
              </button>
              <button 
                onClick={() => setActiveTab('community')}
                style={{ background: activeTab === 'community' ? 'var(--color-primary)' : 'none', border: 'none', color: 'white', padding: '6px 12px', borderRadius: '6px', cursor: 'pointer', fontSize: '13px', display: 'flex', alignItems: 'center', gap: '6px' }}
              >
                <MessageCircle size={14} /> Community DM
              </button>
            </div>
          </div>

          <div style={{ flex: 1, position: 'relative' }}>
            <button 
              onClick={() => {
                const text = activeTab === 'email' ? generateEmail(selectedLead) : activeTab === 'brief' ? generateBrief(selectedLead) : generateCommunityPost(selectedLead);
                handleCopy(text);
              }}
              style={{ position: 'absolute', top: '10px', right: '10px', background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.1)', color: 'white', padding: '6px 12px', borderRadius: '6px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '6px', fontSize: '12px', zIndex: 10 }}
            >
              {copied ? <Check size={14} style={{ color: 'var(--color-success)' }} /> : <Copy size={14} />} {copied ? 'Copied' : 'Copy Content'}
            </button>

            {activeTab === 'email' && (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
                <div style={{ background: 'rgba(139, 92, 246, 0.05)', border: '1px solid rgba(139, 92, 246, 0.1)', padding: '12px', borderRadius: '8px', fontSize: '12px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <Sparkles size={14} style={{ color: 'var(--color-primary)' }} />
                  <span><strong>Agent 11:</strong> Tailored email script adapting tone for {selectedLead.targetTier} account.</span>
                </div>
                <textarea readOnly value={generateEmail(selectedLead)} style={{ width: '100%', height: '350px', background: 'rgba(0,0,0,0.2)', border: '1px solid var(--border-glow)', borderRadius: '8px', padding: '15px', color: '#e2e8f0', fontSize: '13px', lineHeight: '1.6', fontFamily: 'var(--font-sans)', resize: 'none' }} />
              </div>
            )}

            {activeTab === 'brief' && (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
                <pre style={{ width: '100%', height: '380px', background: 'rgba(0,0,0,0.4)', border: '1px solid var(--border-glow)', borderRadius: '8px', padding: '15px', color: '#e2e8f0', fontSize: '12px', fontFamily: 'var(--font-mono)', overflowY: 'auto', whiteSpace: 'pre-wrap' }}>
                  {generateBrief(selectedLead)}
                </pre>
              </div>
            )}

            {activeTab === 'community' && (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
                <div style={{ background: 'rgba(6, 182, 212, 0.05)', border: '1px solid rgba(6, 182, 212, 0.1)', padding: '12px', borderRadius: '8px', fontSize: '12px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <MessageCircle size={14} style={{ color: 'var(--color-secondary)' }} />
                  <span><strong>Agent 15:</strong> Formulated community outreach script for Facebook Groups / Nextdoor.</span>
                </div>
                <textarea readOnly value={generateCommunityPost(selectedLead)} style={{ width: '100%', height: '350px', background: 'rgba(0,0,0,0.4)', border: '1px solid var(--border-glow)', borderRadius: '8px', padding: '15px', color: '#e2e8f0', fontSize: '13px', lineHeight: '1.6', fontFamily: 'var(--font-mono)', resize: 'none' }} />
              </div>
            )}
          </div>

        </div>
      ) : null}

    </div>
  );
};
